
const qlist_g = [[
    "He might be right.",
    "You should see the movie.",
    "If you know the truth, please tell me.",
    "The girl came singing a song.",
    "Shall we dance one more time?",
    "Don't leave me alone.",
    "You may come in.",
    "Yes, what do you want?",
    "I put on my shoes.",
    "All you need is love.",
    "This is hard to do.",
    'He said, "I love you".',
    "I am satisfied with you.",
    "Shall I do it for you?",
    "Do you mind opening the window?",
    "I am glad to see you.",
    "I have many things to do.",
    "He must be the spy.",
    "I know that you are right.",
    "Thank you very much for your kindness.",
    "How many classes do you have today?",
    "I have some questions about the test.",
    "Are you looking for a new shirt? Then come to our store!",
    "How was your trip to Canada?",
    "Do you have any plans for vacation?",
],[
    "He seems to like you.",
    "We are going to stay for a while.",
    "I don't understand what you are saying.",
    "May all your christmas be white.",
    "He runs faster than his dog.",
    "I am now independent of my parents.",
    "The sun having set, we started home.",
    "He is not as tall as I.",
    "He is taller than I by five inches.",
    "She must be crazy to do such a thing.",
    "I heard someone shout.",
    "Her absence disappointed me.",
    "He is no better than yesterday.",
    "Many years have passed since he died.",
    "It has been raining these three days.",
    "He went out just as I came in.",
    "If I had time, I could help you.",
    "I like boxing better than any other sport.",
    "[Charlie] is not my pet, but my friend.",
    "It is kind of you to help me.",
    "I am eating a lot of vegetables.",
    "I finish my job at five every day.",
    "I went to the town where I was born.",
    "You must do it if you want to survive.",
    "To tell the truth, I didn't go to school.",
    "She is the most popular singer in the [Philippines].",
    "Don't you smell something burning?",
        "How often do you have dance lessons?",
        "Let's meet in front of the movie theater at noon.",
        "Come over here and look at this! I can't believe it!",
        "Can I have two hamburgers and a salad?",
        "Get on the bus here, and get off at the last bus stop.",
        "Canada has a lot of nature and wild animals.",
        "I'm just a little tired because I went to bed late last night.",
        "Did you see my key anywhere?",
        "How far is it from here to the station?",
        "The rainy season begins in June. We get a lot of rain during this period.",
        "The dog looked around the room, sat down, and went to sleep.",
        "I slept for only two hours last night, so I'm sleepy now. ",
        "Don't worry, everything will be fine. Trust me.",
        "I'm going to have dinner with my aunt and uncle.",
    ],[
        "Do you play any musical instruments?",
        "I Play the violin, but I'm not very good at it.",
        "I'm learning English conversation from a native speaker.",
        "We are doing an interesting experiment in science class.",
        "Can you solve this math problem?",
        "The bookstore sells many kinds of comic books and weekly magazines.",
        "Members of the basketball team run ten miles every morning.",
        "The weather will be cloudy in the morning, but in the afternoon it will be sunny with no wind.",
        "In America, many schools have a cafeteria, but in Japan, we usually have lunch in the classroom.",
        "I have good news! I won first prize in the speech contest.",
        "I am surprised that you know so much about me.",
        "She insisted on my paying the bill.",
        "It would be good to be with you.",
        "You cannot make yourself understood in English.",
        "We all expect you to pass the exam.",
        "Whatever you say, I have decided to leave.",
        "Never have I seen such a beautiful sight.",
        "It is dangerous for a small kid to play in a bath tub.",
        "If it should go wrong, I will take the responsibility.",
        "Someone has left the water running.",
        "I filled the glass with water.",
        "She didn't know how much he was depressed.",
        "It's a pity that you can't come.",
        "It doesn't matter how you do it.",
        "She welcomes me whenever I visit her.",
        "This is the way he manages the company.",
        "You are too young to know the truth.",
        "On leaving school, she went into show business.",
        "This is the reason I quit the company.",
        "Having no money, the man had to walk home.",
        "She welcomes me, no matter when I visit her.",
        "He would often come to see me on Sundays.",
        "Since I was not prepared, I did not know what to do.",
        "It is surprising that she should do such a thing.",
        "I had finished breakfast when he came to pick me up.",
        "Seen from here, my house looks like a small stone.",
        "I need a new pair of socks. These socks have holes in them.",
        "Can I have another pair of chopsticks? I dropped mine on the floor.",
        "I can make curry and rice. It's one of my favorite dishes.",
        "The Internet is convenient. We can look up information quickly and easily.",
    ],[
        "If I were a woman, things would be interesting.",
        "The light went on and off.",
        "Pass me what is before you.",
        "I am sitting for an exam tomorrow.",
        "People do not like to be kept waiting.",
        "It was not until I came home that I had known the news.",
        "He arrived after everything had settled down.",
        "Nothing is more disgusting than to find a hair in the dish.",
        "Had I known it, I would have told you.",
        "Were I a bird, I could fly to you.",
        "She is talented in the field of performing art.",
        "She didn't know why he was depressed.",
        "She didn't know whether he was really depressed or not.",
        "It makes no difference who leads the team.",
        "I didn't recognize you, because you wore dark glasses.",
        "What a dictionary says is not always correct.",
        "If I were to die now, you would be suspected.",
        "The trouble is that I don't know how he looks.",
        "When I was a child, I was afraid of the dark.",
        "I just stood there while he was talking over the telephone.",
        "She is such a kind woman that everyone calls her [Mom].",
        "I had my picture taken by the great [Buddha].",
        "The photographer took a picture of the white flowers in the garden.",
        "In [Hawaii], we stayed at a hotel near the beach. The view from our room was amazing.",
        "I went to the post office and sent a package by air mail.",
        "A group of boys are flying kites in the field.",
        "I fell from my bike on my way to school.",
        "[Mr. Ozawa]'s son is also a musician. But unlike his father, he plays the guitar.",
        "Japan is an island country, but a lot of different countries had a great influence on Japan.",
        //"I often go shopping at ABC store. They sell nice clothes.",
    ], [
        "Dinner is at eight PM, so come back home before then.",
        "[Mr. Green] laid his hand on his son's shoulder and said, \"Be honest.\"",
        "\"We will arrive in [Seoul] at five. Please enjoy the flight,\" the pilot said to the passengers.",
        "Mr. Sanders will go to Asia on business next week. He will visit several countries.",
        "The plane flew up and disappeared into the clouds.",
        "I aimed at the bull's eye.",
        "I drove at 96 kilometers per hour.",
        "You are old enough to leave us.",
        "It is fun to play pool with you.",
        "I suppose the man to have been on the scene.",
        "The news that the President received an invitation from [Kremlin] is false.",
        "No one is so old that he cannot learn a new thing.",
        "If I had not met you, I might have been single up till now.",
        "Wait till I come back.",
        "He is the tallest of all.",
        "I stayed though I hated it.",
        "He is said to have a great fortune.",
        "There is no telling what may come next.",
        "It pays to work hard when you are young.",
        "I will have been awake for 24 hours in an hour.",
        "[John Lennon] was not only a great musician, but also a mentor to our generation.",
        "In 1939, when the [World War II] began, he left Germany and went to the U.S.",
        "As he was a [Catholic], he was not allowed to divorce.",
        "Be careful in underwriting a contract.",
        "What do you think is the greatest threat to man?",
        "It was you that shot my brother in [Arizona] last year.",
        "What happened? Why are your pants so dirty?",
    ],
];


let unused = {"removed": [
    "Man will make mistakes.",
    "Look before you leap.",
    "I eat a lot of vegetables.",
    "No matter what you say, I have decided to leave.",
    "I'll make you happy.",
    "I've finished my work.",
    "I put them on.",
    "We elected him chairman.",
    "What a dull fellow!",
    "I was born poor.",
    "The door would not open.",
    "I wish you were here.",
    "Keep the child from the pond.",
    "He is as competent as any worker.",
    "It is no use crying over spilt milk.",
    "He can be wrong.",
    "I'll make him go.",
    "I'll have him go.",
    "I'll let him go.",
    "It's OK with me.",
    "I found him pleased.",
    "He may be right.",
    "I saw her come.",
    "You shall be sorry.",
    "I'll fight for you.",
    "I've seen the movie.",
    "I saw her coming.",
    "I am what I am.",
    "I would not do that.",
    "To live is to love.",
    "I have come for the money.",
    "I want you to eat it.",
    "You should have seen the movie.",
    "We all rushed for his rescue.",
    "F.B.I. stands for Federal Bureau of Investigation.",
    "She didn't know that he was depressed.",
    "In the room was an old man.",
    "She cannot run any faster than a mole.",
    "He behaves as if he were my boss.",
    "She went out, her dog barking in the house.",
    "We started at dawn, reaching the destination after sunset.",
    "She went out with her dog barking in the house.",
    "I want you to do this.",
    "He told me that he loved me.",
]};

console.log(JSON.stringify(qlist_g));


const qlist_b = [
{"id":117,"en":"In my mind, I knew that I was wrong.","ss":1,"ws":9,"ja":"心の中では、自分が間違っていることをわかっていた。"},
{"id":278,"en":"In spring, these branches will be covered with leaves.","ss":1,"ws":9,"ja":"春になると、これらの枝は葉でおおわれるでしょう。"},
{"id":29,"en":"I'm learning English conversation from a native speaker.","ss":1,"ws":8,"ja":"私は英語を母語とする人に英会話を学んでいます。"},
{"id":31,"en":"We are doing an interesting experiment in science class.","ss":1,"ws":9,"ja":"私たちは理科の授業で面白い実験をしています。"},
{"id":230,"en":"Milk helps to make your bones strong and healthy.","ss":1,"ws":9,"ja":"牛乳は骨を強くそして健康にすることを手助けしてくれます。"},
{"id":113,"en":"Explaining things in English is difficult.","ss":1,"ws":6,"ja":"英語で物事を説明するのは難しい。"},
{"id":155,"en":"[Tina] covered her nose and mouth with a handkerchief.","ss":1,"ws":9,"ja":"ティナはハンカチで鼻と口をおおいました。"},
{"id":255,"en":"It's dangerous to put a burning candle beside the bed.","ss":1,"ws":10,"ja":"ベッドのそばに燃えているキャンドルを置くのは危険だ。"},
{"id":271,"en":"The hotel guests have their meals in the dining room.","ss":1,"ws":10,"ja":"ホテルのお客さんたちは食堂で食事をします。"},
{"id":67,"en":"The plane flew up and disappeared into the clouds.","ss":1,"ws":9,"ja":"飛行機は上に飛んでいき、雲の中に消えていった。"},
{"id":96,"en":"would you go and get some eggs at the supermarket?","ss":1,"ws":10,"ja":"スーパーに卵を買いに行ってきてくれない？"},
{"id":260,"en":"The store only sells fresh vegetables grown on local farms.","ss":1,"ws":10,"ja":"その店は、地域の農場で育てられた新鮮な野菜だけを売っています。"},
{"id":273,"en":"The dog barked with joy when his master came home.","ss":1,"ws":10,"ja":"その犬は、主人が帰宅すると、喜んでほえた。"},
{"id":205,"en":"The car crashed into a wall at a high speed.","ss":1,"ws":10,"ja":"その車は速いスピードで壁にぶつかった。"},
{"id":202,"en":"The farmer has more than fifty cows on his farm.","ss":1,"ws":10,"ja":"その農場経営者は、農場に50頭以上の牛を飼っています。"},
{"id":28,"en":"A group of boys are flying kites in the field.","ss":1,"ws":10,"ja":"男の子の一群が原っぱでたこあげをしています。"},
{"id":267,"en":"My dad works for a company that makes electric toys.","ss":1,"ws":10,"ja":"父は、電気のおもちゃを作る会社に勤めています。"},
{"id":207,"en":"The runner set a new record in the 100-meter race.","ss":1,"ws":10,"ja":"その走者は、100メートル走で新記録を出しました。"},
{"id":248,"en":"The daughter of a king queen is called a princess.","ss":1,"ws":10,"ja":"王あるいは女王の娘は王女といいます。"},
{"id":40,"en":"Members of the basketball team run ten miles every morning.","ss":1,"ws":10,"ja":"バスケットボール部の部員は毎朝10マイル走ります。"},
{"id":156,"en":"[Tommy] is a very clever kid with a rich imagination.","ss":1,"ws":10,"ja":"トミーは豊かな想像力を持ったかしこい子だ。"},
{"id":171,"en":"[Mr. King]'s brave actions gave courage to millions of people.","ss":1,"ws":10,"ja":"キング氏の勇敢な行動は、何百人もの人に勇気を与えました。"},
{"id":246,"en":"A lot of rocks were used to build this castle.","ss":1,"ws":10,"ja":"この城を建てるのにたくさんの岩が使われました。"},
{"id":188,"en":"Although there was some trouble, the spaceship somehow landed safely.","ss":1,"ws":10,"ja":"いくらかのトラブルはありましたが、その宇宙船は、何とか無事に着陸しました。"},
{"id":9,"en":"Please write your name, phone number and e-mail address here.","ss":1,"ws":10,"ja":"あなたの名前と電話番号とメールアドレスをここに書いてください。"},
{"id":263,"en":"Somebody shouted my name, but I didn't know who it was.","ss":1,"ws":11,"ja":"だれかが私の名前を叫んだが、私はそれがだれだかわからなかった。"},
{"id":216,"en":"[Ricky] is a polite boy, but he doesn't follow the rules.","ss":1,"ws":11,"ja":"リッキーは礼儀正しい少年ですが、規則を守りません。"},
{"id":209,"en":"Her gesture had a very important meaning, but nobody realized it.","ss":1,"ws":11,"ja":"彼女のジェスチャーはとても重要な意味を持っていましたが、だれもそれに気づきませんでした。"},
{"id":198,"en":"For the latest information on our products, check our company homepage.","ss":1,"ws":11,"ja":"当社の製品に関する最新情報については、当社ホームページをご覧ください。"},
{"id":122,"en":"You shouldn't take a bath when you have a high fever.","ss":1,"ws":11,"ja":"高い熱があるときはお風呂に入らないほうがいいですよ。"},
{"id":218,"en":"I was so nervous that I couldn't express my thoughts well.","ss":1,"ws":11,"ja":"私はあまりにも緊張していたので、自分の考えをうまく表現することができなかった。"},
{"id":215,"en":"During the discussion, [Mary] shook her head and said, I disagree.","ss":1,"ws":11,"ja":"話し合いの間、メアリーは首を横に振り「私はそう思わない」と言いました。"},
{"id":39,"en":"The bookstore sells many kinds of comic books and weekly magazines.","ss":1,"ws":11,"ja":"その書店はいろいろな種類のまんが本や週刊誌を売っています。"},
{"id":252,"en":"His eyes were filled with tears when he won the match.","ss":1,"ws":11,"ja":"試合に勝ったとき、彼の目は涙でいっぱいだった。"},
{"id":139,"en":"The purpose of this meeting is to choose our next leader.","ss":1,"ws":11,"ja":"このミーティングの目的は、私たちの次のリーダーを選ぶことです。"},
{"id":240,"en":"Dear Mom, A month has passed since I came to Spain.","ss":1,"ws":11,"ja":"お母さんへ、スペインに来てから1か月がたちました。"},
{"id":236,"en":"The thief saw a police officer and hid behind a car.","ss":1,"ws":11,"ja":"どろぼうは警察官を見て、車の後ろに隠れた。"},
{"id":250,"en":"A part of the apartment building was damaged by the fire.","ss":1,"ws":11,"ja":"アパートの一部はその火事で損害を受けました。"},
{"id":177,"en":"[Lisa] lay down on her bed, spread her arms, and breathed deeply.","ss":1,"ws":12,"ja":"リサはベッドの上で横になり、腕を広げ、深く呼吸した。"},
{"id":187,"en":"Astronauts go through many years of training before they go to space.","ss":1,"ws":12,"ja":"宇宙飛行士は、宇宙に行く前に何年もの訓練を受けます。"},
{"id":245,"en":"Even if we leave now, it's impossible to arrive there in time.","ss":1,"ws":12,"ja":"たとえ今出発したとしても、そこに間に合うように到着するのは不可能だよ。少なくとも1時間はかかるんだ。"},
{"id":161,"en":"In our everyday life, we waste a lot of water and electricity.","ss":1,"ws":12,"ja":"日常生活の中で、私たちはたくさんの水と電気をむだにしています。"},
{"id":249,"en":"Many books are stolen every year, the owner of the bookshop complained.","ss":1,"ws":12,"ja":"「毎年たくさんの本が盗まれています」と、その書店の店主は不平を言いました。"},
{"id":228,"en":"As citizens of this world, we have a responsibility to preserve nature.","ss":1,"ws":12,"ja":"この世界の市民として、私たちには自然を保護する責任があります。"},
{"id":121,"en":"When you travel abroad, you must show your passport at the airport.","ss":1,"ws":12,"ja":"海外に旅行するときは、空港でパスポートを見せなければいけません。"},
{"id":120,"en":"[Miss Thomas] was preparing dinner in the kitchen when the bell rang.","ss":1,"ws":12,"ja":"ベルが鳴ったとき、トーマスさんはキッチンで夕飯の準備をしていた。"},
{"id":257,"en":"[Reiko] noticed an old woman standing nearby, so she offered her seat.","ss":1,"ws":12,"ja":"レイコは、近くに立っているお年寄りの女の人に気づいたので、自分の席をゆずりました。"},
{"id":62,"en":"The photographer took a picture of the white flowers in the garden.","ss":1,"ws":12,"ja":"その写真家は、庭の白い花の写真をとった。"},
{"id":58,"en":"The dog looked around the room, sat down, and went to sleep.","ss":1,"ws":12,"ja":"その犬は部屋を見渡し、すわり、そして眠りました。"},
{"id":127,"en":"I woke up at six but I couldn't get out of bed.","ss":1,"ws":12,"ja":"ぼくは6時に目が覚めた。だけど、ベッドから出ることができなかった。"},
{"id":281,"en":"The reporter rushed to the site of the attack to gather more information.","ss":1,"ws":13,"ja":"報道記者はもっと多くの情報を集めるため、攻撃が行われた場所に急いで行った。"},
{"id":286,"en":"As soon as possible, we must think of ways to prevent further accidents.","ss":1,"ws":13,"ja":"できるだけ早く、私たちはさらなる事故を防ぐ方法を考えなければいけません。"},
{"id":150,"en":"Before leaving the house, turn off the lights and close all the windows.","ss":1,"ws":13,"ja":"家を出る前に電気を消して窓を全部閉めてね。"},
{"id":68,"en":"I went to the post office and sent a package by air mail.","ss":1,"ws":13,"ja":"私は郵便局に行って、小包を航空便で送りました。"},
{"id":107,"en":"He likes to sit on the bench in the park and draw pictures.","ss":1,"ws":13,"ja":"彼は公園のベンチにすわって絵を描くのが好きです。"},
{"id":123,"en":"In Japan, we always take off our shoes when we enter our hpomes.","ss":1,"ws":13,"ja":"日本では、家に入るときはいつもくつを脱ぎます。"},
{"id":124,"en":"While we were in China, our neighbor took care of our pet bird.","ss":1,"ws":13,"ja":"私たちが中国に行っている間は、隣人がペットの鳥の面倒を見てくれました。"},
{"id":70,"en":"[Mr. Green] laid his hand on his son's shoulder and said, Be honest.","ss":1,"ws":13,"ja":"グリーンさんは息子の方に手をのせて、「正直になれ」と言った。"},
{"id":279,"en":"Various environmental groups are working to protect the environment and our natural resources.","ss":1,"ws":13,"ja":"いろいろな環境団体が、環境と自然資源を守るために活動しています。"},
{"id":135,"en":"I tried to climb the large hill with my bicycle, but I couldn't.","ss":1,"ws":13,"ja":"ぼくは自転車でその大きな丘を登ろうとしたが、できなかった。"},
{"id":206,"en":"The topic of today's class is the cause and effect of climate change.","ss":1,"ws":13,"ja":"今日の授業の話題は、気候変化の原因と結果です。"},
{"id":195,"en":"It's a little cool outside, but I don't think a jacket is necessary.","ss":1,"ws":13,"ja":"外はすずしいけど、ジャケットは必要ないと思うよ。"},
{"id":295,"en":"My favorite subject is P.E., and my least favorite subject is social studies.","ss":1,"ws":13,"ja":"ぼくのいちばん好きな科目は体育で、最も嫌いな科目は社会科です。"},
{"id":141,"en":"I like listening to the radio since there are many interesting language programs.","ss":1,"ws":13,"ja":"私はラジオを聞くのが好きです。たくさんのおもしろい語学番組があります。"},
{"id":213,"en":"The waiter greeted the customer with a smile, and then took his order.","ss":1,"ws":13,"ja":"ウェイターはお客さんに笑顔であいさつをし、それから注文をとりました。"},
{"id":152,"en":"I'm taller than [Eric], but [Greg] is the tallest of the three of us.","ss":1,"ws":14,"ja":"ぼくはエリックよりも背が高いけど、グレッグがぼくたち3人の中でいちばん背が高い。"},
{"id":276,"en":"The police officer tried his best, but he could not discover any new facts.","ss":1,"ws":14,"ja":"その警察官はベストを尽くしたが、新たな事実を発見することはできなかった。"},
{"id":193,"en":"The city hall is planning a campaign to plant flowers all over the city.","ss":1,"ws":14,"ja":"市役所は、街じゅうに花を植えるキャンペーンを計画しています。"},
{"id":266,"en":"[Ms. Arakawa] is an athlete who won the gold medal in the Olympic Games.","ss":1,"ws":14,"ja":"荒川さんは、オリンピックで金メダルをとった選手です。"},
{"id":219,"en":"These days, our schedules are so busy that we can't spend much time together.","ss":1,"ws":14,"ja":"近ごろ、私たちのスケジュールはあまりにも忙しくて、あまりいっしょに時間を過ごせていません。"},
{"id":264,"en":"A stranger came up to me and asked me where the Cultural Canter was.","ss":1,"ws":14,"ja":"見知らぬ人が私に近づいてきて、文化センターがどこにあるかをたずねた。"},
{"id":110,"en":"In winter, many foreigners from Australia and other countries come to Hokkaido to ski.","ss":1,"ws":14,"ja":"冬には、オーストラリアやほかの国からの多くの外国人が北海道にスキーをしに来ます。"},
{"id":229,"en":"The little girl asked Santa Claus to bring her a pretty doll for Christmas.","ss":1,"ws":14,"ja":"その幼い少女は、クリスマスにかわいい人形を持ってきてくれるようにサンタクロースに頼みました。"},
{"id":128,"en":"After my brother graduated from college, he became an engineer in the computer industry.","ss":1,"ws":14,"ja":"ぼくの兄は大学を卒業したあと、コンピュータ産業の技術になりました。"},
{"id":180,"en":"Western breakfasts are becoming popular in Japan, but I prefer rice and miso soup.","ss":1,"ws":14,"ja":"日本では西洋風の朝食がはやり始めていますが、私はごはんとみそ汁のほうが好きです。"},
{"id":287,"en":"[Armstrong] was the first human being to step on the surface of the moon.","ss":1,"ws":14,"ja":"アームストロングは、月の表面をふんだ最初の人間です。"},
{"id":176,"en":"[Mr. Adams] spoke little Japanese, so I had to communicate with him in English.","ss":1,"ws":14,"ja":"アダムズさんはほとんど日本語が話せなかったので、私は彼と英語で意思を伝え合わないといけなかった。"},
{"id":208,"en":"Most people like tea, especially green tea, but coffee is also popular among adults.","ss":1,"ws":14,"ja":"ほとんどの人はお茶、特に緑茶が好きです。でも、大人の間では、コーヒーも人気です。"},
{"id":258,"en":"The driver looked away from the road and almost hit a girl crossing the street.","ss":1,"ws":15,"ja":"運転手は道路から目をそらし、道を横断している女の子にぶつかりそうになった。"},
{"id":45,"en":"[Mr. Ozawa]'s son is also a musician, but unlike his father, he plays the guitar.","ss":1,"ws":15,"ja":"小沢さんの息子もまた音楽家です。しかし、父と違って、彼はギターをひきます。"},
{"id":72,"en":"There is a door at the front side and the back side of the house.","ss":1,"ws":15,"ja":"家の前側と後ろ側にドアがあります。"},
{"id":214,"en":"When the bank clerks were counting the money, a man with a gun suddenly appeared.","ss":1,"ws":15,"ja":"銀行員がお金を数えていたとき、銃を持った男が突然現れた。"},
{"id":181,"en":"There was a terrible car accident on this corner yesterday, but fortunately no one died.","ss":1,"ws":15,"ja":"昨日、この角でおそろしい自動車事故がありましたが、幸いにもだれも死にませんでした。"},
{"id":119,"en":"The sign in the park says that visitors must not give food to the fish.","ss":1,"ws":15,"ja":"公演の標識には、訪問者は魚にエサをやってはいけないと書いてあります。"},
{"id":237,"en":"I've lived in Tokyo for over five years, but I've never been to Tokyo Tower.","ss":1,"ws":15,"ja":"私は5年以上東京に住んでいます。でも一度も東京タワーに行ったことがありません。"},
{"id":115,"en":"My father wants a new TV, but my mother says that we don't need one.","ss":1,"ws":15,"ja":"ぼくの父は新しいテレビをほしがっています。でも、母は、私たちには必要ないと言っています。"},
{"id":227,"en":"The gentleman put a ring on the lady's finger and said, Will you marry me?","ss":1,"ws":15,"ja":"その紳士は、女性の指に指輪をはめ「結婚してくれますか」と言った。"},
{"id":225,"en":"Perhaps someday, a person will be able to live on another planet besides the earth.","ss":1,"ws":15,"ja":"たぶん、いつか、人は地球とはほかに、別の惑星で生活することができるだろう。"},
{"id":192,"en":"During my homestay, I had a chance to talk with people from different ethnic groups.","ss":1,"ws":15,"ja":"ホームステイ中、私はさまざまな民族の人々と話す機会がありました。"},
{"id":102,"en":"I found a nice hat at the department store, but I didn't have enough money.","ss":1,"ws":15,"ja":"デパートですてきな帽子を見つけたけど、十分なお金がありませんでした。"},
{"id":137,"en":"My baseball coach says that you have to use your whole body to throw the ball.","ss":1,"ws":16,"ja":"ぼくの野球のコーチは、ボールを投げるには体全体を使わなければいけないと言っています。"},
{"id":296,"en":"To reduce air pollution, we should use bikes instead of cars when we travel short distances.","ss":1,"ws":16,"ja":"大気汚染を減らすために、私たちは短い距離を移動するときは、車の代わりに自転車を使うべきだ。"},
{"id":149,"en":"In the interview, the actor talked about his past and his reason for becoming an actor.","ss":1,"ws":16,"ja":"そのインタビューの中で、その俳優は自分の過去について、また、俳優になった理由について話をした。"},
{"id":184,"en":"When the singer appeared on the stage, the excited audience stood up and clapped their hands.","ss":1,"ws":16,"ja":"その歌手がステージに現れると、興奮した観客は立ち上がって拍手をしました。"},
{"id":179,"en":"[Beth] took a look at herself in the mirror, and then went out of the bathroom.","ss":1,"ws":16,"ja":"べスは鏡の中の自分自身をちらっと見て、それからトイレを出ました。"},
{"id":244,"en":"It's not good manners to talk in a loud voice when you are riding on trains.","ss":1,"ws":16,"ja":"電車に乗っているときに大声で話すのはよいマナーではありません。"},
{"id":212,"en":"I got a bottle of juice and a bag of potato chips at the convenience store.","ss":1,"ws":16,"ja":"ぼくはジュース1本とポテトチップス1袋をコンビニで買いました。"},
{"id":226,"en":"When I looked down at the ground from the top of the tower, my knees shook.","ss":1,"ws":16,"ja":"塔のてっぺんから地面を見下ろしたとき、私のひざはがくがくした。"},
{"id":272,"en":"Both the apple pie and the chocolate cookies look delicious., Let's get both and share them.","ss":1,"ws":16,"ja":"アップルパイもチョコレートクッキーもおいしそうね。, 両方買って、分け合おうよ。"},
{"id":297,"en":"I think communication can help to develop understanding between the younger generation and the older generation.","ss":1,"ws":16,"ja":"私はコミュニケーションによって、若い世代と年配の世代との間で理解を深めることができると思う。"},
{"id":80,"en":"'We will arrive in [Seoul] at five. Please enjoy the flight, the pilot said to the passengers.',","ss":1,"ws":17,"ja":"「5時にソウルに到着します。どうぞ空の旅をお楽しみください」とパイロットは乗客に言った。"},
{"id":223,"en":"New York has many sightseeing sports such as the Statue of Liberty, [Trinity Church], and so on.","ss":1,"ws":17,"ja":"ニューヨークには、自由の女神やトリニティ教会などのようなたくさんの観光スポットがあります。"},
{"id":293,"en":"According to this article, during the twentieth century, the average temperature in Tokyo increased by three degrees.","ss":1,"ws":17,"ja":"この記事によると、20世紀の間に、東京の平均気温は3度上昇しました。"},
{"id":63,"en":"Japan is an island country, but a lot of different countries had a great influence on Japan.","ss":1,"ws":17,"ja":"日本は島国です。しかし、多くのいろいろな国が日本に大きく影響をおよぼしました。"},
{"id":46,"en":"In America, many schools have a cafeteria, but in Japan, we usually have lunch in the classroom.","ss":1,"ws":17,"ja":"アメリカでは、多くの学校に食堂があります。しかし日本では、私たちはふつう教室で昼食を食べます。"},
{"id":289,"en":"I used to think that reading books was boring, but now it's my favorite thing to do.","ss":1,"ws":17,"ja":"ぼくは前は本を読むことはつまらないと思っていた。だけど、今では、いちばん好きなことだ。"},
{"id":251,"en":"I was shocked when I got the results of the exam since I was expecting a better score.","ss":1,"ws":18,"ja":"ぼくは試験の結果を受け取ったちきにショックを受けました。ぼくはもっとよい点数を期待していました。"},
{"id":174,"en":"I have basic knowledge of English, but sometimes I have a difficult time when I read long sentences.","ss":1,"ws":18,"ja":"私は英語の基本的な知識を持っています。だけど、ときどき長い文を読むときに苦労します。"},
{"id":101,"en":"Walk along this street, turn right at the second traffic light, and you'll see the hospital on your left.","ss":1,"ws":19,"ja":"この通りに沿って歩いて、2つ目の信号を右に曲がってください。すると、左手にその病院が見えます。"},
{"id":290,"en":"At first [Ron] was very shy, but after a while, he got used to school, and he gradually changed.","ss":1,"ws":19,"ja":"最初は、ロンはとてもはずかしがりやでした。でもしばらくすると、彼は学校に慣れ、だんだんと変わっていきました。"},
{"id":77,"en":"The weather will be cloudy in the morning, but in the afternoon, it will be sunny with no wind.","ss":1,"ws":19,"ja":"天気は、朝はくもりでしょう。しかし午後は、晴れて風もないでしょう。"},
{"id":148,"en":"I'm looking forward to going to high school, but I'm sad to say goodbye to my junior high school friends.","ss":1,"ws":20,"ja":"私は高校に行くのが楽しみです。だけど、中学の友だちに別れを告げるのはさびしいです。"},
{"id":1,"en":"I am [Eriko] from Tokyo Japan. I am fourteen years old.","ss":2,"ws":11,"ja":"日本の東京から来たエリコです。14歳です。"},
{"id":38,"en":"Oh no, I'm in trouble. What's the matter?","ss":2,"ws":8,"ja":"まずい、困ったなあ。, どうしたの？"},
{"id":8,"en":"OK, everyone. Look at the camera and smile.","ss":2,"ws":8,"ja":"はい、みんな。カメラを見て笑って！"},
{"id":74,"en":"Your homework is perfect. There are no mistakes.","ss":2,"ws":8,"ja":"あなたの宿題は完ぺきです。1つもミスがありません。"},
{"id":76,"en":"Don't worry. Everything will be fine. Trust me.","ss":3,"ws":8,"ja":"心配しないで、アン。すべてうまくいくから。ぼくを信じて。"},
{"id":20,"en":"Be careful. Don't touch the pot. It's very hot.","ss":3,"ws":9,"ja":"気をつけて、ジョン。なべにさわらないで。とても熱いから。"},
{"id":4,"en":"When is the school festival? It's next weekend.","ss":2,"ws":8,"ja":"学校祭はいつですか。, 次の週末です。"},
{"id":6,"en":"Excuse me. How much is this? - It's one thousand two hundred yen.","ss":3,"ws":13,"ja":"すみません、これはいくらですか。, 1,200円です。"},
{"id":75,"en":"I'll write you again soon. Take care. Sincerely, [John].","ss":3,"ws":9,"ja":"またすぐあなたに手紙を書きます。気をつけてね。敬具。"},
{"id":24,"en":"This is sashimi. It's raw fish. Why don't you try it? No, thanks. I'm full.","ss":5,"ws":15,"ja":"これは刺身だよ。生の魚なんだ。ためしてみなよ。, いえ、結構です。おなかいっぱいです。"},
{"id":86,"en":"Hello. This is [Ann]. May I speak to [Bill], please? Oh, hi, Ann. This is Bill.","ss":5,"ws":16,"ja":"もしもし、アンと申しますが、ビル君はいますか。, あ、やあ、アン。ビルだよ。"},
{"id":41,"en":"How do you read this word? [Tegami]. It means letter.","ss":3,"ws":10,"ja":"さやか、この単語どう読むの。, テガミ。「手紙」という意味よ。"},
{"id":94,"en":"Excuse me, sir. Could you take a photo of us? No problem. Are you ready? Say cheese!","ss":5,"ws":17,"ja":"すみません。私たちの写真をとっていただけますか。, もちろん。準備はいいかい？ はい、チーズ！"},
{"id":2,"en":"What day is it today? It's Tuesday.","ss":2,"ws":7,"ja":"今日は何曜日ですか。, 火曜日です。"},
{"id":3,"en":"What's the date today? It's April 1.","ss":2,"ws":7,"ja":"今日は何日ですか。, 4月1日です。"},
{"id":97,"en":"Shall I wash the dishes? No, it's OK. I'll do it.","ss":3,"ws":11,"ja":"ぼくがお皿を洗いましょうか。, いいえ、大丈夫です。私がやります。"},
{"id":34,"en":"Can I have two hamburgers and a salad? Sure. Anything else?","ss":3,"ws":11,"ja":"ハンバーガー2つとサラダをいただけますか。, はい。何かほかには？"},
{"id":47,"en":"Whose dictionary is this? It's mine. I got it just recently.","ss":3,"ws":11,"ja":"これはだれの辞書？, ぼくのだよ。つい最近買ったんだ。"},
{"id":105,"en":"Do you have an extra pen? Yeah. Here you go. I'll lend you this one.","ss":4,"ws":15,"ja":"余分なペンを持っている？, うん。はい、これを貸してあげるよ。"},
{"id":235,"en":"Are you busy next weekend? Hold on. Let me check my calender.","ss":3,"ws":12,"ja":"やあ、パット。来週の週末は忙しい？, ちょっと待って。カレンダーをチェックさせて。"},
{"id":23,"en":"[Ms. Taylor], I have some questions about the test. Sure. Go ahead.","ss":3,"ws":12,"ja":"テイラー先生、テストについていくつか質問があるのですが。, わかりました、フレッド。どうぞ。"},
{"id":16,"en":"Do you have any pets? I have a rabbit. It's really cute. It has long ears.","ss":4,"ws":16,"ja":"何かペットは飼っているの？, ウサギを飼っているよ。本当にかわいいよ。長い耳をしているんだ。"},
{"id":280,"en":"Look, there is a mouse there! Is it dead? No, its tail is moving. It's alive.","ss":4,"ws":16,"ja":"見て、あそこにねずみがいる！ 死んでる？, いや、しっぽが動いているよ。生きているよ。"},
{"id":98,"en":"Shall we take a rest? Yes. I'm thirsty. Let's sit in the shade of that tree.","ss":4,"ws":16,"ja":"休憩しましょうか。, はい。のどがかわきました。あの木の陰にすわりましょう。"},
{"id":27,"en":"Hi, Sarah, this is Mike. What are you doing right now? I'm watching TV at home. Why?","ss":4,"ws":17,"ja":"やあ、サラ。マイクだよ。今何をしているの？, いえでテレビを見ているの。どうして？"},
{"id":232,"en":"Please open the door. No, go away! I don't want to talk to anyone. Leave me alone.","ss":4,"ws":17,"ja":"シンディー、お願いだからドアを開けて。, いや、どこか行って！ だれとも話したくないの。1人にして。"},
{"id":37,"en":"Can you solve this math problem? Let me see. Oh, yes it's easy.","ss":3,"ws":13,"ja":"この数学の問題解ける？, ええと。ああ、うん、簡単だよ。"},
{"id":14,"en":"I don't have a map. How about you? I don't have one either.","ss":3,"ws":13,"ja":"私は地図を持っていません。あなたはどうですか。, 私も持っていません。"},
{"id":222,"en":"[Mrs. Thomas] is a nurse. She takes care of patients with serious diseases.","ss":3,"ws":13,"ja":"トーマスさんは看護師です。彼女は重病の患者さんの世話をしています。"},
{"id":26,"en":"Is it already seven fifty? Yes, hurry up! Class starts in ten minutes!","ss":3,"ws":13,"ja":"もう7時50分なの？, そうよ、急ぎなさい！ 10分で授業が始まるよ！"},
{"id":217,"en":"Let's go inside. It's too dark to play catch.","ss":2,"ws":9,"ja":"中に入ろう。キャッチボールをするには暗すぎる。"},
{"id":134,"en":"Can I have a piece of paper? I forgot to bring my notebook. － Sure. Here you are.","ss":4,"ws":18,"ja":"ユミ、紙を1枚もらっていい？ ノートを持ってくるのを忘れちゃったんだ。－ もちろん。はい、どうぞ。"},
{"id":5,"en":"Do you know [Adam]? I know him well. He's a good friend of mine.","ss":3,"ws":14,"ja":"アダムを知っていますか。よく知っています。ぼくのよい友だちです。"},
{"id":111,"en":"Would you like something to drink? Yes. I'd like a cup of tea, please.","ss":3,"ws":14,"ja":"何かお飲み物はいかがですか。, はい。お茶を1杯ください。"},
{"id":154,"en":"Which do you like better, cats or dogs? That's hard question. Both are cute.","ss":3,"ws":14,"ja":"あなたはねこと犬ではどちらがより好きですか。, それは難しい質問ね。両方ともかわいいよ。"},
{"id":17,"en":"Dinner is at eight pm, so come back home before then. OK, Mom. Bye!","ss":3,"ws":14,"ja":"夕食は午後8時だから、その前に帰ってきてね。, わかったよ、お母さん。じゃあね！"},
{"id":35,"en":"Happy birthday, Kate! This is a present for you., Thanks! Can I open it?","ss":3,"ws":14,"ja":"誕生日おめでとう、ケイト。これはきみへのプレゼントだよ。, ありがとう！ 開けてもいい？"},
{"id":13,"en":"Is this [Yuki]'s tennis racket? No it's not hers. She uses a black one.","ss":3,"ws":14,"ja":"これはユキのテニスラケット？, いや、それは彼女のものじゃないよ。彼女は黒いのを使っているよ。"},
{"id":21,"en":"Let's meet in front of the movie theater at noon. Sounds good. See you soon.","ss":3,"ws":15,"ja":"正午に映画館の前で会おう。, いいわね。じゃ、またすぐにね。"},
{"id":201,"en":"[Lucy] is my best friend. She is smart and kind. She has a warm heart.","ss":3,"ws":15,"ja":"ルーシーは私の親友です。彼女は頭がよくて親切です。彼女は温かい心を持っています。"},
{"id":18,"en":"Thank you very much for your kindness. It's my pleasure.","ss":2,"ws":10,"ja":"ご親切にどうもありがとうございます。, どういたしまして。"},
{"id":234,"en":"Those boxes look heavy. I'll help you carry them. Oh thanks, that's kind of you.","ss":3,"ws":15,"ja":"それらの箱は重そうだね。運ぶの手伝ってあげるよ。, あ、ありがとう、グレッグ。優しいのね。"},
{"id":33,"en":"Come over here and look at this! I can't believe it!, What? What is it?","ss":3,"ws":15,"ja":"こっちに来て、これを見て！ 信じられないよ！, 何？ 何なの？"},
{"id":19,"en":"How often do you have dance lessons? Twice a week.","ss":2,"ws":10,"ja":"ダンスのレッスンは何回あるの？, 週に2回です。"},
{"id":82,"en":"Do you have any plans for vacation? Yes. I'm going to a hot spring with my family. I can't wait.","ss":4,"ws":20,"ja":"休暇の予定は何かあるの？, はい、家族と温泉に行きます。待ちきれません。"},
{"id":93,"en":"Pardon me? I couldn't hear you because of the noise.","ss":2,"ws":10,"ja":"もう一度言ってくださいますか？ 雑音のせいで聞こえませんでした。"},
{"id":108,"en":"I'd like introduce my friend to you. This is [Gordon].","ss":2,"ws":10,"ja":"クリス、僕の友だちをきみに紹介したいんだけど。彼はゴードンというんだ。"},
{"id":90,"en":"You don't have to be afraid. This snake doesn't bite.","ss":2,"ws":10,"ja":"こわがらなくていいよ。このヘビはかまないよ。"},
{"id":131,"en":"[Linda] is coming to my house after school. Can you come, too? － It sounds like fun. I'd love to go.","ss":4,"ws":21,"ja":"放課後、リンダが私の家にお来るんだ。きみも来られる？ － おもしろそうね。ぜひ行きたいわ。"},
{"id":87,"en":"I'm afraid he is not in his office right now. May I take a message? That's OK. I'll call back later.","ss":4,"ws":21,"ja":"彼は今オフィスにいません。ご伝言をうかがいましょうか。, いえ、結構です。あとでかけなおします。"},
{"id":88,"en":"How long can I borrow these books? Two weeks. You must return them by May 5.","ss":3,"ws":16,"ja":"これらの本はどのくらい長く借りられるのですか。, 2週間です。5月5日までに返さなければいけません。"},
{"id":133,"en":"Did you remember to call [David]? － Oh, no, I forgot! I'll call him right now.","ss":3,"ws":16,"ja":"デイビッドに電話するのを覚えてた？ － しまった。忘れていた！ 今かけるよ。"},
{"id":224,"en":"Thanks to your advice, I was able to pass the test. Thank you. － Not at all. I'm glad I could help.","ss":4,"ws":22,"ja":"あなたの助言のおかげで試験に合格できたよ。ありがとう。－ どういたしまして。力になれてうれしいわ。"},
{"id":186,"en":"The restaurant was crowded and noisy. I didn't feel comfortable there.","ss":2,"ws":11,"ja":"そのレストランはこんでいて騒がしかった。私はそこで心地よい感じはしませんでした。"},
{"id":130,"en":"What time is your concert this weekend? I'd like to go.","ss":2,"ws":11,"ja":"今週末のコンサートは何時？ 行きたいな。"},
{"id":15,"en":"I like your T-shirt. I actually have one like it, too.","ss":2,"ws":11,"ja":"あなたのTシャツいいね、サラ。私も実はそれに似たのを持っているの。"},
{"id":43,"en":"I often go shopping at ABC store. They sell nice clothes.","ss":2,"ws":11,"ja":"私はよくABC店に買い物に行きます。そこではよい洋服を売っています。"},
{"id":274,"en":"In case of emergency, use the stairs. Don't use the elevator.","ss":2,"ws":11,"ja":"緊急事態の場合は、階段を使ってください。エレベーターは使わないでください。"},
{"id":168,"en":"I'm confident that I can succeed. Please give me a chance.","ss":2,"ws":11,"ja":"私は成功する自信があります。私に機会をください。"},
{"id":25,"en":"I like that pianist. I have many of her CDs. The sound of her piano is special.","ss":3,"ws":17,"ja":"私はあのピアニストが好きです。彼女のCDの多くを持っています。彼女のピアノの音は特別です。"},
{"id":59,"en":"Can I have another pair of chopsticks? I dropped mine on the floor., Certainly. Just a moment.","ss":3,"ws":17,"ja":"おはしをもう一膳いただけますか。床に落としてしまいました。, かしこまりました。少々お待ちください。"},
{"id":54,"en":"How far is it from here to the station? It's about one kilometer. It takes ten minutes.","ss":3,"ws":17,"ja":"ここから駅まで距離はどれくらいですか。, 1キロくらいです。10分かかります。"},
{"id":42,"en":"It's such a wonderful day today. Why don't we go to the zoo? That's a great idea!","ss":3,"ws":17,"ja":"今日はこんなにすばらしい天気だよ。動物園に行こうか？, それはすごくいい考えね！"},
{"id":132,"en":"[Ken] loves to sing. His dream is to become a professional singer.","ss":2,"ws":12,"ja":"ケンは歌を歌うのが大好きです。彼の夢はプロの歌手になることです。"},
{"id":203,"en":"I hear that and more people in the U.S. are cooking Japanese food at home. Is this true?","ss":3,"ws":18,"ja":"ますます多くのアメリカ人が自宅で日本料理を作っているそうですが、本当ですか。"},
{"id":95,"en":"Excuse me. I'd like a ticket for the three o'clock performance, please.","ss":2,"ws":12,"ja":"すみません、3時の公演のチケットを1枚ください。"},
{"id":221,"en":"This isn't a normal knife. It's a special one for cutting bread.","ss":2,"ws":12,"ja":"これはふつうのナイフではありません。これはパンを切るための特別なものです。"},
{"id":69,"en":"What happened? Why are your pants so dirty? I fell from my bike on my way to school.","ss":3,"ws":18,"ja":"どうしたの？ なんでそんなズボンが汚れているの？, 学校へ行く途中、自転車から落ちちゃったんだ。"},
{"id":160,"en":"Your feet are really wet. Here, use this towel and dry yourself.","ss":2,"ws":12,"ja":"足がびしょびしょにぬれているじゃない。はい、このタオルを使って乾かしなさい。"},
{"id":100,"en":"[Ken] should be the captain of the team., Year. I think so,too.","ss":2,"ws":12,"ja":"ケンがチームのキャプテンになるべきだわ。, うん、ぼくもそう思うよ。"},
{"id":84,"en":"[Tom] is studying in his room. He has an important exam tomorrow.","ss":2,"ws":12,"ja":"トムは自分の部屋で勉強しているよ。明日大事な試験があるんだよ。"},
{"id":158,"en":"Books are important. However, we can learn some things only through experience.","ss":2,"ws":12,"ja":"本は大事です。しかしながら、経験を通して学べないことがあります。"},
{"id":66,"en":"The TV broke again., Are you kidding? This is the third time.","ss":2,"ws":12,"ja":"テレビがまたこわれたよ。, うそでしょ？これで3回目だよ。"},
{"id":30,"en":"Are you looking for a new shirt? Then come to our store!","ss":2,"ws":12,"ja":"新しいシャツをお探しですか？ でしたら、私たちのお店にお越しください。"},
{"id":61,"en":"The Internet is convenient. We can look up information quickly and easily.","ss":2,"ws":12,"ja":"インターネットは便利です。私たちは情報をすばやく簡単に調べることができます。"},
{"id":241,"en":"I've finished! Finally, I can go home, the tired worker said happily.","ss":2,"ws":12,"ja":"「終わった！ やっと家に帰れる」と疲れた労働者はうれしそうに言った。"},
{"id":32,"en":"I can make curry and rice. It's one of my favorite dishes.","ss":2,"ws":12,"ja":"ぼくはカレーライスが作れます。それはぼくの大好きな料理の1つです。"},
{"id":247,"en":"The artist is widely known. He is popular everywhere is the world.","ss":2,"ws":12,"ja":"その芸術家は、幅広く知られている。彼は世界中どこでも人気がある。"},
{"id":231,"en":"Music has strange powers. When I feel sad, music makes me happier.","ss":2,"ws":12,"ja":"音楽は不思議な力を持っています。悲しい気分のとき、音楽は私をより幸せにしてくれます。"},
{"id":126,"en":"I'm hungry. Let's take a lunch break before we continue our work.","ss":2,"ws":12,"ja":"おなかが空いたわ。仕事を続ける前に、ランチの休憩をとりましょう。"},
{"id":10,"en":"Where are you from? I'm from a small village in [Nagano] Prefecture.","ss":2,"ws":12,"ja":"出身はどこですか？, 長野県の小さな村の出身です。"},
{"id":52,"en":"What's wrong, Mary? You're quiet today., I'm just a little tired. I went to bed late last night.","ss":3,"ws":18,"ja":"どうしたの、メアリー。今日は静かだね。, ただちょっと疲れているだけ。昨夜遅く寝たの。"},
{"id":51,"en":"How was your trip to Canada? It was great. Canada has a lot of nature and wild animals.","ss":3,"ws":18,"ja":"カナダへの旅行はどうでしたか。, 最高でした。カナダにはたくさんの自然があり、野生の動物がいます。"},
{"id":36,"en":"Can you get my coat? It's on the desk over there., I see two coats. Which is yours?","ss":3,"ws":18,"ja":"私のコートを取ってくれる？ そこの机の上にあるの。, コートは2つ見えるよ。どっちがきみの？"},
{"id":79,"en":"Is the University near here? Yes. Go straight for two blocks and you'll see it on your right.","ss":3,"ws":18,"ja":"ABC大学はこの近くですか。, はい。2ブロックまっすぐ行くと、右手に見えます。"},
{"id":189,"en":"My grandfather likes to collect rare stamps. He has an impressive collection.","ss":2,"ws":12,"ja":"ぼくの祖父は珍しい切手を集めるのが好きです。彼は印象深いコレクションを持っています。"},
{"id":147,"en":"Did you enjoy yourself at the party yesterday? Yes, I had a very good time. Thanks for inviting me.","ss":3,"ws":19,"ja":"サム、昨日のパーティーは楽しんだ？, うん、とても楽しい時間だったよ。招待してくれてありがとう。"},
{"id":64,"en":"Mom, This apple is delicious. It's really sweet., Oh, is it? I got it at a new fruit store.","ss":3,"ws":19,"ja":"お母さん、このりんごとてもおいしい。すごく甘いよ。, あら、そう？ 新しい果物店で買ったのよ。"},
{"id":71,"en":"My father and I went fishing yesterday. We caught a lot of fish and ate them. They tasted great.","ss":3,"ws":19,"ja":"昨日、お父さんとぼくは釣りに行きました。たくさん魚をつかまえて食べました。すごくおいしかった。"},
{"id":191,"en":"I belong to the tennis club. We have practice every day. Our goal is to win the national championship.","ss":3,"ws":19,"ja":"私はテニス部に所属しています。私たちは毎日練習があります。目標は全国大会で優勝することです。"},
{"id":7,"en":"Who is that man with the glasses? He is our new English teacher.","ss":2,"ws":13,"ja":"あのめがねをかけた男性はだれ？, 彼は私たちの新しい英語の先生です。"},
{"id":146,"en":"Don't be afraid of making mistakes. Just have fun and do your best.","ss":2,"ws":13,"ja":"間違えることを恐れないで。とにかく楽しんで、ベストを尽くして。"},
{"id":288,"en":"[Mr. Black] is a cheerful person. He likes telling jokes and funny stories.","ss":2,"ws":13,"ja":"ブラックさんは明るい人です。彼は冗談やおもしろい話を言うのが好きです。"},
{"id":142,"en":"The singer has a soft, low voice. Listening to his songs relaxes me.","ss":2,"ws":13,"ja":"その歌手は、やわらかくて低い声をしています。彼の歌を聞くと落ち着きます。"},
{"id":157,"en":"[George] doesn't have a wallet. He puts all his coins in his pocket.","ss":2,"ws":13,"ja":"ジョージは財布を持っていません。彼は、コインを全部ポケットに入れています。"},
{"id":104,"en":"The salesclerk was very helpful. He gave us a lot of useful advice.","ss":2,"ws":13,"ja":"その店員さんはとても助けになりました。彼は私たちにたくさんの役立つアドバイスをくれました。"},
{"id":136,"en":"I'm saving money to buy a video game. The game is twenty dollars.","ss":2,"ws":13,"ja":"私はテレビゲームを買うためにお金をためています。そのゲームは20ドルです。"},
{"id":99,"en":"New York is famous for its museums. You should visit some this summer.","ss":2,"ws":13,"ja":"ニューヨークは博物館で有名だよ。この夏にいくつか訪れてみるといいよ。"},
{"id":262,"en":"Can you guess who built this temple? the tour guide asked the tourists.","ss":2,"ws":13,"ja":"「この寺を建てたのはだれか当てられますか」と旅行ガイドは観光客たちに尋ねました。"},
{"id":291,"en":"My coach told me to trust my own abilities. Her words encouraged me.","ss":2,"ws":13,"ja":"私のコーチは、私に自分自身の能力を信じるようにと言った。彼女の言葉は私を勇気づけました。"},
{"id":11,"en":"My host family is very nice. My classmates are friendly to me, too.","ss":2,"ws":13,"ja":"ぼくのホストファミリーはとても親切です。クラスメイトもぼくに親しくしてくれています。"},
{"id":204,"en":"Cherry blossoms are a symbol of Japan. They have a beautiful pink color.","ss":2,"ws":13,"ja":"桜の花は日本の象徴です。美しいピンクの色をしています。"},
{"id":265,"en":"I wonder why Jim is late. It's unusual for him to be late.","ss":2,"ws":13,"ja":"どうしてジムは遅れているのだろう。彼が遅刻するのは珍しいことだ。"},
{"id":92,"en":"Could you turn off the air conditioner, please? I feel a little cold.","ss":2,"ws":13,"ja":"エアコンを消してくれますか？ 少し寒く感じます。"},
{"id":56,"en":"I need a new pair of socks. These socks have holes in them.","ss":2,"ws":13,"ja":"新しいくつ下が必要です。このくつ下は穴があいています。"},
{"id":103,"en":"Excuse me, could you tell me the way to the public library? Sure.","ss":2,"ws":13,"ja":"すみません、公共図書館までの行き方を教えてくれますか。, いいですよ。"},
{"id":116,"en":"Here, this is a gift for you. I got it at a market in Singapore. I hope you like it.","ss":3,"ws":20,"ja":"はい、これはきみへの贈り物だよ。シンガポールの市場で買ったんだ。気に入ってくれるといいんだけど。"},
{"id":164,"en":"The bridge over the river looked old. I didn't want to walk across it.","ss":2,"ws":14,"ja":"川にかけてあるその橋は古そうに見えた。私はそれを歩いて渡りたくなかった。"},
{"id":165,"en":"Don't tell Mom anything about the birthday cake yet. I want to surprise her.","ss":2,"ws":14,"ja":"お母さんには誕生日ケーキのことはまだ何も言わないでね。驚かせたいの。"},
{"id":243,"en":"Even my grandparents can use the Web. I'll teach you how to use it.","ss":2,"ws":14,"ja":"ぼくの祖父母でさえもインターネットを使えるよ。使い方を教えてあげるね。"},
{"id":284,"en":"Teammates must support each other. A single team member can't do everything by himself.","ss":2,"ws":14,"ja":"チームメイトはお互いに支え合わなければいけません。たった1人の選手が1人ですべてのことはできません。"},
{"id":109,"en":"What club are you going to join? I decided to join the soccer club.","ss":2,"ws":14,"ja":"何のクラブに入るの？, サッカー部に入ることにしたよ。"},
{"id":170,"en":"Italy is a great place for sightseeing. There are many World Heritage sites there.","ss":2,"ws":14,"ja":"イタリアは観光にとてもよい場所です。そこはたくさんの世界遺産があります。"},
{"id":60,"en":"Your eyes are red., I'm sleepy. I slept for only two hours last night.","ss":2,"ws":14,"ja":"目が赤いよ、ジェームズ。, 眠いんだ。昨夜、2時間しか寝てないんだ。"},
{"id":190,"en":"The education system in Japan is changing. Elementary schools are starting to teach English.","ss":2,"ws":14,"ja":"日本の教育制度は変化しています。小学校が英語を教え始めています。"},
{"id":114,"en":"Tomorrow is a holiday. Let's do something exciting., How about going to the movies?","ss":2,"ws":14,"ja":"明日は休日だよ。何かわくわくすることしようよ。, 映画を見に行くのはどう？"},
{"id":200,"en":"How is the pain in your stomach? It's getting better, but it still hurts.","ss":2,"ws":14,"ja":"おなかの痛みはどう？, よくなってきているけど、まだ痛いよ。"},
{"id":53,"en":"Did you see my key anywhere? It was under the chair in the bedroom.","ss":2,"ws":14,"ja":"ぼくのかぎどこかで見た？, うん。寝室にあったよ。いすの下にあった。"},
{"id":162,"en":"I agree with [Jack]'s opinion. We should reduce trash, and we should recycle more.","ss":2,"ws":14,"ja":"私はジャックの意見に賛成です。私たちはゴミを減らして、もっとリサイクルをするべきです。"},
{"id":163,"en":"The [ALT] pronounced the alphabet slowly. The students listened carefully and repeated after him.","ss":2,"ws":14,"ja":"ALTはアルファベットをゆっくり発音しました。生徒たちは注意深く聞き、彼のあとをくり返しました。"},
{"id":261,"en":"[Andy] compared bananas from different countries. He liked bananas produced in Brazil the best.","ss":2,"ws":14,"ja":"アンディはさまざまな国のバナナを比較しました。彼はブラジルで生産されたバナナがいちばん好きでした。"},
{"id":55,"en":"The rainy season begins in June. We get a lot of rain during this period.","ss":2,"ws":15,"ja":"梅雨の季節は6月に始まります。この期間の間、たくさんの雨が降ります。"},
{"id":151,"en":"Don't use a mobile phone when you drive. You should pay attention to your driving.","ss":2,"ws":15,"ja":"運転をするときに携帯電話を使ってはいけません。運転に注意を払うべきです。"},
{"id":153,"en":"Mt. Fuji is the highest mountain in Japan. It is famous for its beautiful shape.","ss":2,"ws":15,"ja":"富士山は日本でいちばん高い山です。それはその美しい形で有名です。"},
{"id":210,"en":"We had a barbecue in our yard yesterday. I cooked chicken for the first time.","ss":2,"ws":15,"ja":"昨日、庭でバーベキューをしました。私は初めてとり肉を料理しました。"},
{"id":78,"en":"[Mr. Sanders] will go to Asia on business next week. He will visit several countries.","ss":2,"ws":15,"ja":"サンダースさんは来週仕事でアジアに行きます。彼はいくつかの国々を訪問する予定です。"},
{"id":49,"en":"Kyoto is a city with a long history. It was once the capital of Japan.","ss":2,"ws":15,"ja":"京都は長い歴史をもつ都市です。それはかつて日本の首都でした。"},
{"id":173,"en":"It was my cousin's wedding yesterday. I almost cried when she and her husband kissed.","ss":2,"ws":15,"ja":"昨日は私のいとこの結婚式でした。彼女と夫がキスをしたとき、私は泣きそうになりました。"},
{"id":233,"en":"The police have an important job. They fight against crime and keep the community safe.","ss":2,"ws":15,"ja":"警察には大切な仕事があります。彼らは犯罪と戦い、地域社会を安全に保ちます。"},
{"id":178,"en":"[Ben] brushed his teeth. He then combed his hair and put on his school uniform.","ss":2,"ws":15,"ja":"ベンは歯を磨きました。それから髪をとかし、学校の制服を着ました。"},
{"id":140,"en":"If you have any questions, just raise your hands. I'll be happy to answer them.","ss":2,"ws":15,"ja":"もし質問があったら、ただ手をあげてください。私は喜んでお答えします。"},
{"id":81,"en":"Are you free tonight? Sorry, I'm going to have dinner with my aunt and uncle.","ss":2,"ws":15,"ja":"今夜はひま？, ごめん、おばとおじと夕食を食べる予定なんだ。"},
{"id":256,"en":"The elderly man looked at the setting sun and sighed. It was a beautiful sunset.","ss":2,"ws":15,"ja":"そのお年寄りの男性は沈んでいく太陽を見てため息をついた。美しい日没でした。"},
{"id":292,"en":"They didn't have freedom of expression. The government didn't allow people to say things freely.","ss":2,"ws":15,"ja":"彼らには表現の自由がありませんでした。政府は人々が物事を自由に言うことを許さなかったのです。"},
{"id":65,"en":"I worked as a volunteer during spring vacation. We cleaned the park in our town.","ss":2,"ws":15,"ja":"私は春休みの間、ボランティアとして働きました。私たちは町の公園をきれいにしました。"},
{"id":125,"en":"I lost my cell phone today. My parents got angry because it was quite expensive.","ss":2,"ws":15,"ja":"ぼくは今日、携帯電話をなくしてしまいました。それは相当高かったので、ぼきうの両親は怒りました。"},
{"id":220,"en":"This TV drama is about friendship, happiness, and the real meaning of life. It's worth watching.","ss":2,"ws":16,"ja":"このテレビドラマは友情、幸福、そして人生の本当の意味についてのものです。見る価値があります。"},
{"id":106,"en":"What do you want to be in the future? I want to be a doctor. I want to help sick people in poor countries.","ss":3,"ws":24,"ja":"あなたは将来何になりたいですか。, 医者になりたいです。貧しい国に住む病気の人たちを助けたいです。"},
{"id":199,"en":"I don't think war is the solution. I think there are more peaceful ways than fighting.","ss":2,"ws":16,"ja":"私は、戦争が解決策だとは思いません。戦うことよりももっと平和な方法があると思います。"},
{"id":277,"en":"Each person has their own opinions and feelings. We should understand that and respect the differences.","ss":2,"ws":16,"ja":"それぞれの人が自分自身の意見や感情を持っています。私たちはそれを理解し、違いを尊重するべきです。"},
{"id":275,"en":"When [Mrs. Tani] feels confused, scared, or disappointed, she writes down her feelings in her diary.","ss":2,"ws":16,"ja":"谷さんは、混乱したり、こわかったり、失望したりしたときは、日記に気持ちを書きとめます。"},
{"id":167,"en":"My grandma became very ill last year. Her illness taught me the importance of good health.","ss":2,"ws":16,"ja":"私のおばあちゃんは昨年、重病になりました。彼女の病気は、私に健康の大切さを教えてくれました。"},
{"id":283,"en":"He has a very positive attitude toward life. He fears nothing, and he worries about nothing.","ss":2,"ws":16,"ja":"彼は人生に対してとても前向きな態度を持っている。彼は何も恐れないし、何についても心配しない。"},
{"id":145,"en":"Sending New Year's cards is a common Japanese custom. Children and adults send cards to friends.","ss":2,"ws":16,"ja":"年賀状を送ることは一般的な日本の習慣です。子どもや大人が友達にカードを送ります。"},
{"id":138,"en":"This coffee machines is simple to use. Just put water into it and push this button.","ss":2,"ws":16,"ja":"このコーヒーメーカーは、使うのが簡単です。ただの水をその中に入れて、このボタンを押してください。"},
{"id":73,"en":"In volleyball, there are six players on each team. You can change players during the game.","ss":2,"ws":16,"ja":"バレーボールでは、それぞれのチームに6人の選手がいます。試合中に選手を替えることができます。"},
{"id":259,"en":"My dad is a big fan of European furniture. He only buys furniture made in Europe.","ss":2,"ws":16,"ja":"私の父はヨーロッパの家具の大ファンです。彼はヨーロッパで作られた家具しか買いません。"},
{"id":91,"en":"I got up at four thirty this morning., Wow, that's early. You must be sleepy then.","ss":2,"ws":16,"ja":"ぼくは今朝4時30分に起きました。, わぁ、それは早いね。そしたら、眠いにちがいないわね。"},
{"id":12,"en":"Do you play any musical instruments? I Play the violin, but I'm not very good at it.","ss":2,"ws":17,"ja":"何か楽器はひくの？ - バイオリンをひくけど、あまりじょうずじゃないんだ。"},
{"id":166,"en":"I'll tell you the truth, but it's a secret so don't tell anybody. I promise I won't.","ss":2,"ws":17,"ja":"あなたに真実をお話します。でも、秘密ですのでだれにも言わないでください。, 言いません。約束します。"},
{"id":159,"en":"I'm surprised that you know a lot about American culture. I'm very interested in the United States.","ss":2,"ws":17,"ja":"驚いたわ。アメリカの文化についてよく知っているのね。, うん。アメリカにすごく興味があるんだ。"},
{"id":57,"en":"In [Hawaii], we stayed at a hotel near the beach. The view from our room was amazing.","ss":2,"ws":17,"ja":"ハワイでは、私たちは浜辺のそばのホテルに泊まりました。部屋からの景色は見事でした。"},
{"id":269,"en":"I want to be a scientist. I want to invent something that will change people's loves forever.","ss":2,"ws":17,"ja":"ぼくは科学者になりたいです。ぼくは、人々の生活を永遠に変える何かを発明したいです。"},
{"id":143,"en":"Put the cups in the sink after you finish using them. Don't leave them on the table.","ss":2,"ws":17,"ja":"使い終わったら、カップは流しに入れてください。テーブルに置いたままにしないでください。"},
{"id":172,"en":"[Bob], take your gloves with you when you go out. The newspaper says it's going to snow.","ss":2,"ws":17,"ja":"ボブ、外出するときは手袋を持っていくんだよ。新聞によると、雪が降るそうだよ。"},
{"id":129,"en":"Long ago, people thought the earth was flat. Now, of course, we know that it is round.","ss":2,"ws":17,"ja":"ずっと昔、人々は地球が平らだと思っていた。今はもちろん、私たちは地球が丸いということを知っている。"},
{"id":118,"en":"A lot of foreign people don't like natto. They say it smells bad, but [Ben] loves it.","ss":2,"ws":17,"ja":"多くの外国の人が納豆を嫌います。彼らはくさいにおいがするといいます。でもベンは大好きです。"},
{"id":169,"en":"The population f the world is rising. Today, there are nearly seven billion people in the world.","ss":2,"ws":17,"ja":"世界の人口は増えています。こんにち、世界で70億人近くいます。"},
{"id":239,"en":"Though it has been 10 years, I clearly remember that day. It still lives in my memory.","ss":2,"ws":17,"ja":"もう10年たつけれど、その日のことをはっきりと覚えています。まだ記憶に残っています。"},
{"id":211,"en":"[Mamoru] is a friend from my hometown. We went to the same nursery school a d kindergarten.","ss":2,"ws":17,"ja":"マモルはぼくの故郷の友だちです。ぼくたちは同じ保育園と幼稚園に行っていました。"},
{"id":253,"en":"A welcome party was held for the international exchange students. They seemed happy to be in Japan.","ss":2,"ws":17,"ja":"国際交換留学生のために歓迎会が開かれた。彼らは、日本に来てうれしそうだった。"},
{"id":185,"en":"In Japanese society, people bow in many situations. For example, we bow when we say thank you.","ss":2,"ws":17,"ja":"日本の社会では、多くの場面で人々はおじぎをします。たとえば「ありがとう」を言うときにおじぎをします。"},
{"id":270,"en":"This is a famous poem by [Basho]. It is about a frog which jumps into a silent pond.","ss":2,"ws":18,"ja":"これは芭蕉による有名な詩です。静かな池の中に飛び込むカエルについてです。"},
{"id":285,"en":"[Perry]'s visit to Japan was a historic event. After the visit, Japan worked on becoming a modern country.","ss":2,"ws":18,"ja":"ペリーの日本への訪問は歴史的な出来事だった。その訪問後、日本は近代国家になろうと取り組んだ。"},
{"id":85,"en":"I'm sorry, but will you start the meeting without me? I missed the bus and will be late.","ss":2,"ws":18,"ja":"悪いんだけど、私ぬきで打ち合わせを始めてもらえる？ バスに乗り遅れて、遅れるから。"},
{"id":83,"en":"I'm going to Britain as an exchange student next fall. I'm staying in London for half a year.","ss":2,"ws":18,"ja":"ぼくは次の秋に、交換留学生としてイギリスに行く予定です。半年の間、ロンドンに滞在します。"},
{"id":238,"en":"Have you ever read any books by Matsumoto Seicho? Yes, I've read a couple of his mystery novels.","ss":2,"ws":18,"ja":"今までに松本清張の本は何か読んだことある？, うん。彼の推理小説を2、3冊読んだことがあるよ。"},
{"id":144,"en":"Swimming in the sea is very different from swimming in a pool. There are waves in the sea.","ss":2,"ws":18,"ja":"海で泳ぐことはプールで泳ぐこととは、まったく違います。海には波があります。"},
{"id":112,"en":"I went camping with my family. At night, we enjoyed looking at the bright stars in the sky.","ss":2,"ws":18,"ja":"ぼくは家族とキャンプに行きました。夜は、空の輝く星を見て楽しみました。"},
{"id":175,"en":"[Yuji] visited his grandmother at the nursing home. They talked and laughed, and had a great time together.","ss":2,"ws":18,"ja":"ユウジは老人ホームに祖母を訪ねました。2人はおしゃべりし、笑い、いっしょにすばらしい時間を過ごしました。"},
{"id":183,"en":"Global warming is a serious problem. If we don't stop it, people all over the world will suffer.","ss":2,"ws":18,"ja":"地球温暖化は深刻な問題です。もし地球温暖化を止めないと、世界中の人々が苦しむでしょう。"},
{"id":50,"en":"I was born in Saitama. I lived there until the age of nine, and then moved to Chiba.","ss":2,"ws":18,"ja":"私は埼玉で生まれました。9歳までそこに住み、それから千葉に引っ越しました。"},
{"id":196,"en":"How do people in Japan celebrate New Year's Day? Many families visit shrines to wish for good luck.","ss":2,"ws":18,"ja":"日本の人々はどのように元日を祝うの？, 多くの家族は幸運を祈るために神社に行きます。"},
{"id":182,"en":"I don't know much about art, but I think his paintings are interesting. He paints in a unique style.","ss":2,"ws":19,"ja":"ぼくは芸術についてあまり知らないけど、彼の絵はおもしろいと思う。彼は独特なスタイルで絵をかきます。"},
{"id":242,"en":"I sent Fred an e-mail, but I haven't received a reply yet., That's strange. Maybe he didn't notice it.","ss":2,"ws":19,"ja":"フレッドにメールを送ったけど、まだ返事を受け取ってないんだ。, それは変ね。気づかなかったのかもね。"},
{"id":268,"en":"Let's go cycling tomorrow if it isn't raining. I know a nice cycling path that goes through the forest.","ss":2,"ws":19,"ja":"もし雨が降っていなかったら、明日サイクリングに行こう。森を抜けるいいサイクリングの小道を知っているんだ。"},
{"id":254,"en":"There was an earthquake in the Kanto area this morning. A few people were injured, but none were killed.","ss":2,"ws":19,"ja":"今朝、関東地方で地震がありました。何人かがけがをしましたが、だれも死にませんでした。"},
{"id":89,"en":"I fell down the stairs and broke my leg. Now, I have to use a wheelchair for a while.","ss":2,"ws":19,"ja":"私は階段から落ちて足を骨折しました。今は、しばらくの間、車いすを使わなくてはいけません。"},
{"id":197,"en":"Which train should I take? It's cheaper if you take the Yellow Line, but the Green Line is faster.","ss":2,"ws":19,"ja":"どちらの電車に乗るべきですか。Yellow線に乗るとより安いけど、Green線のほうが速いよ。"},
{"id":48,"en":"Mom, I have good news! I won first prize in the speech contest., I'm so proud of you, Jim.","ss":2,"ws":19,"ja":"お母さん、よい知らせがあるよ。スピーチコンテストで1等賞とったよ。, あなたをすごく誇りに思うわ、ジム。"},
{"id":194,"en":"I have a headache, and I can't stop coughing., You seem to have a cold. Here, take this medicine.","ss":2,"ws":19,"ja":"頭痛がし、せきが止まりません。, かぜをひいているようですね。はい、この薬を飲んでください。"},
{"id":298,"en":"I didn't wear a cap in spite of the strong sunlight. Now, the skin on my face really hurts.","ss":2,"ws":19,"ja":"強い日ざしにも関わらず、ぼくは帽子をかぶりませんでした。それで今、顔の皮がとても痛みます。"},
{"id":22,"en":"How many classes do you have today? I have six classes today, so the last one ends at five thirty.","ss":2,"ws":20,"ja":"今日はいつく授業あるの？, 6つ。最後の授業は5時半に終わるよ。"},
{"id":282,"en":"[Mr. Endo] may not be young, but he is full of energy. He is an active person with many hobbies.","ss":2,"ws":20,"ja":"遠藤さんは若くはないかもしれないが、エネルギーにあふれています。彼は多くの趣味を持った活動的な人です。"},
{"id":294,"en":"My father is getting fat, so he should do more exercise. Also, he should eat less meat and more vegetables.","ss":2,"ws":20,"ja":"私の父は太ってきています。彼はもっと運動をするべきです。また、肉をもっと少なく、野菜をもっと多くとるべきです。"},
{"id":44,"en":"Get on the bus here, and get off at the last bus stop., OK. By the way, how much is the bus fare?","ss":2,"ws":23,"ja":"ここでバスに乗って、最後のバス停で降りてください。, わかりました。ところで、バス料金はいくらですか。"},
];
